language: minimal
before_install:
  - curl -fsSL https://bun.sh/install | bash
  - export PATH="$HOME/.bun/bin:$PATH"
install: bun install
script:
  - bun run lint
  - bun run build
  - bun run test
branches:
  only:
    - master
    - release
    - canary
cache:
  directories:
    - ~/.bun/install/cache
